name: CD - Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/intens-api:latest


      - name: Deploy locally
        run: |
          docker stop intens-api-container || true
          
          docker rm intens-api-container || true
          
          docker pull ${{ secrets.DOCKER_USERNAME }}/intens-api:latest
          
          docker run -d -p 8082:8080 --name intens-api-container ${{ secrets.DOCKER_USERNAME }}/intens-api:latest
